networks:
    ifk_test_network:
        driver: bridge

services:
  php:
    build:
      args:
        user: "${USER_NAME}"
        uid: "${USER_ID}"
      context: ./docker/php
      dockerfile: Dockerfile
    volumes:
      - .:/var/www
    networks:
        - ifk_test_network

  db:
      image: postgres:17.2
      ports:
          - "54320:5432"
      volumes:
          - ./db/postgresql:/var/lib/postgresql/data
      environment:
          - POSTGRES_USER=${POSTGRES_USER:-user}
          - PGUSER=${POSTGRES_USER:-user}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-S3cret}
          - POSTGRES_DB=${POSTGRES_DB:-ifk_tt_db}
      networks:
          - ifk_test_network

  nginx:
      image: nginx:1.25-alpine
      restart: unless-stopped
      ports:
          - "8000:80"
      volumes:
          - ./:/var/www
          - ./docker/nginx/conf.d:/etc/nginx/conf.d
      networks:
          - ifk_test_network
