<?php

namespace App\Infrastructure\Framework;

class Application extends \Illuminate\Foundation\Application
{
//    protected $environmentFile = __DIR__ . "/../../../.env";
//
//    public function boot()
//    {
//        $this->loadEnvironmentFrom($this->environmentFile);
//        parent::boot(); // TODO: Change the autogenerated stub
//        $this->loadEnvironmentFrom($this->environmentFile);
//    }

    public function booting($callback)
    {
        parent::booting($callback); // TODO: Change the autogenerated stub
        $this->loadEnvironmentFrom($this->environmentFile);
    }

    public function loadEnvironmentFrom($file): Application
    {
        return parent::loadEnvironmentFrom("/../../../.env");
    }
}
